name: CI
run-name: ${{ github.actor }} is testing out GitHub Actions
on:
  push:
    branches: 
      - main
      - branchpull
  pull_request:
    types: [ opened, synchronize ]
  workflow_dispatch:
jobs:
  permanent_actions:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
    - run: npm ci
    - run: npm test
