name: CI
run-name: ${{ github.actor }} is testing out GitHub Actions
on:
  push:
    branches: 
      - main
      - branchpull
  pull_request:
    types: [ opened, synchronize ]
  workflow_dispatch:
jobs:
  permanent_actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          sparse-checkout: .
